blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('', views.BlogsView.as_view(), name="blogs"),
    path('create/', views.blog_create_view, name="create_blog"),
    path('subscribe/', views.CreateSubscriptionView.as_view(), name='subscribe'),
    path('<slug:slug>/', views.BlogView.as_view(), name="blog"),
]

chatapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('chat.urls')),
    path('blog/', include('blog.urls'))
] + static(settings.STATIC_URL, document=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Blog(models.Model):
    class Meta:
        ordering = '-created_at',

    title = models.CharField(max_length=250)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super().save()

    def get_absolute_url(self):
        return reverse("blog", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title


class Subscription(models.Model):
    email = models.EmailField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.email

blog/forms.py
from django import forms

from blog.models import Blog


class CreateBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from blog.forms import CreateBlogForm
from blog.models import Blog, Subscription
from blog.tasks import send_blog_email


class BlogsView(ListView):
    model = Blog
    template_name = 'blog/blogs.html'


class BlogView(DetailView):
    model = Blog
    template_name = 'blog/blog.html'


class CreateSubscriptionView(CreateView):
    model = Subscription
    fields = '__all__'
    template_name = 'blog/blogs.html'
    success_url = reverse_lazy('blogs')


@login_required
def blog_create_view(request):
    form = CreateBlogForm()
    if request.method == "POST":
        form = CreateBlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            send_blog_email.delay(blog.title, "Hello sir, hope you do well, we are glad to present you our new blog"
                                              "you can read it here: "
                                              f"https://{request.get_host()}{blog.get_absolute_url()}")
            return redirect('blogs')

    return render(request, 'blog/create-blog.html', context={'form': form})

templates/blog/blog.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% block head %}
	<title>{{ blog.title }}</title>
{% endblock head %}
{% block body %}
	<div class="container mt-5">
		<div class="row d-flex justify-content-between">
			<div class="col-lg-7">
				<!-- Post content-->
				<article>
					<!-- Post header-->
					<header class="mb-4">
						<!-- Post title-->
						<h1 class="fw-bolder mb-1">{{ blog.title }}</h1>
						<!-- Post meta content-->
						<div class="text-muted fst-italic mb-2">Yazılma
							tarixi: {{ blog.created_at }}, {{ blog.author.username }} tərəfindən
						</div>
						<!-- Post categories-->
						<a class="badge bg-secondary text-decoration-none link-light" href="#">Web Design</a>
						<a class="badge bg-secondary text-decoration-none link-light" href="#">Freebies</a>
					</header>
					<!-- Preview image figure-->
					<figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg"
																		alt="..."/></figure>
					<!-- Post content-->
					<section class="mb-5">{{ blog.text|safe }}</section>
				</article>
				<!-- Comments section-->
				<section class="mb-5 ">
					<h3>Şərhlər</h3>
					<div class="card bg-light w-100">
						<div class="card-body">
							<!-- Comment form-->
							{% if request.user.is_authenticated %}
								<h4>Şərh yaz</h4>
								<form class="mb-4" method="post">
									{% csrf_token %}
									<div class="d-flex">
										{% for field in form %}
											{{ field }}
										{% endfor %}
										<button class="mx-2 btn btn-primary" type="submit">Yaz</button>
									</div>
								</form>
							{% else %}
								<h2>Şərh yazmaq üçün <a href="{% url 'login' %}">hesaba daxil olun</a></h2>
							{% endif %}
							<form class="mb-4">
								<textarea class="form-control" rows="3"
													placeholder="Join the discussion and leave a comment!"></textarea>
							</form>
							<!-- Comment with nested comments-->
							<div class="d-flex mb-4">
								<!-- Parent comment-->
								<div class="flex-shrink-0"><img class="rounded-circle"
																								src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."/></div>
								<div class="ms-3">
									<div class="fw-bold">Commenter Name</div>
									If you're going to lead a space frontier, it has to be government; it'll never be private enterprise.
									Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
									<!-- Child comment 1-->
									<div class="d-flex mt-4">
										<div class="flex-shrink-0"><img class="rounded-circle"
																										src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."/>
										</div>
										<div class="ms-3">
											<div class="fw-bold">Commenter Name</div>
											And under those conditions, you cannot establish a capital-market evaluation of that enterprise.
											You can't get investors.
										</div>
									</div>
									<!-- Child comment 2-->
									<div class="d-flex mt-4">
										<div class="flex-shrink-0"><img class="rounded-circle"
																										src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."/>
										</div>
										<div class="ms-3">
											<div class="fw-bold">Commenter Name</div>
											When you put money directly to a problem, it makes a good headline.
										</div>
									</div>
								</div>
							</div>
							<!-- Single comment-->
							{% for comment in article.comments.all %}
								<div class="d-flex">
									{#                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>#}
									<div class="m-2 w-100">
										<div class="d-flex justify-content-between ">
											<div class="fw-bold">{{ comment.owner }}</div>
											<div>{{ comment.created_calc }}</div>
										</div>
										{{ comment.body }}
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</section>
			</div>
			<!-- Side widgets-->
			<div class="col-lg-4 ml-auto">
				<!-- Search widget-->
				<div class="card mb-4 w-100">
					<div class="card-header">Search</div>
					<div class="card-body">
						<div class="input-group">
							<input class="form-control" type="text" placeholder="Enter search term..."
										 aria-label="Enter search term..." aria-describedby="button-search"/>
							<button class="btn btn-primary" id="button-search" type="button">Go!</button>
						</div>
					</div>
				</div>
				<!-- Categories widget-->
				<div class="card mb-4 w-100">
					<div class="card-header">Categories</div>
					<div class="card-body">
						<div class="row">
							<div class="col-sm-6">
								<ul class="list-unstyled mb-0">
									<li><a href="#!">Web Design</a></li>
									<li><a href="#!">HTML</a></li>
									<li><a href="#!">Freebies</a></li>
								</ul>
							</div>
							<div class="col-sm-6">
								<ul class="list-unstyled mb-0">
									<li><a href="#!">JavaScript</a></li>
									<li><a href="#!">CSS</a></li>
									<li><a href="#!">Tutorials</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<!-- Side widget-->
				<div class="card mb-4 w-100">
					<div class="card-header">Side Widget</div>
					<div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and
						feature the Bootstrap 5 card component!
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer-->
	<footer class="py-5 bg-dark">
		<div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
	</footer>
	<!-- Bootstrap core JS-->
	{#        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>#}
	<!-- Core theme JS-->
	{#        <script src="js/scripts.js"></script>#}

{% endblock body %}

templates/blog/blogs.html
{% extends 'index.html' %}
{% block title %}
	Blogs
{% endblock %}
{% block body %}
	<div class="container">
		{% for blog in blog_list %}
			<div class="card my-2">
				<div class="card-header">
					{{ blog.author }}
				</div>
				<div class="card-body">
					<h5 class="card-title">{{ blog.title }}</h5>
					<p class="card-text">{{ blog.text|truncatechars:100 }}</p>
					<a href="{{ blog.get_absolute_url }}" class="btn btn-primary">Read more</a>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/blog/create-blog.html
{% extends 'index.html' %}
{% block title %}
	Create blog
{% endblock %}
{% block body %}
	<div class="container">
		<form method="post">
			{% csrf_token %}
			<div class="mb-3">
				<label for="title" class="form-label">{{ form.title.label }}</label>
				{{ form.title }}
			</div>
			<div class="mb-3">
				<label for="text" class="form-label">{{ form.text.label }}</label>
				{{ form.text }}
			</div>
			<input type="submit" value="Create" class="btn btn-primary">
			{{ form.errors }}
		</form>
	</div>
{% endblock %}